spring:
  application:
    name: hnc-auth
  profiles:
    active: test
  main:
    web-application-type: none

logging:
  path: ./logs

dubbo:
  scan:
    base-packages: com.fengjx.hello.netty.chat.auth.service
  registry:
    address: zookeeper://127.0.0.1:2181
    file: ${user.home}/dubbo-cache/${spring.application.name}/dubbo.cache
  protocol:
    name: dubbo
    port: -1